# This is a docker compose file for Nginx server deployments
# Project: https://gitlab.com/richardnagy/container-environments/server-deployments

version: '3'
services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
