# This is a docker compose file for Angular server deployments
# Project: https://gitlab.com/richardnagy/container-environments/server-deployments

version: '3'
services:
  angular:
    container_name: angular
    hostname: angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
