# This is a docker compose file for Apache server deployments
# Project: https://gitlab.com/richardnagy/container-environments/server-deployments

version: '3'
services:
  apache:
    container_name: apache
    hostname: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
